### PR TITLE
[UPDATE] Fix + update network-requester-setup doc

### PR DESCRIPTION
**Pull request by twofaktor**
## Description

The NYM Network Requester, as a client component within the NYM network, operates by sending requests to other nodes for the purpose of routing and processing network traffic. In this context, **it is not required** for the Network Requester **to receive incoming requests** from other nodes within the network.

The primary role of the **Network Requester is to initiate outbound connections** to the NYM network (gateway in concrete)

By focusing on outbound connections and relying on the gateway node, the **Network Requester doesn't need incoming connections.**

## How

- [X] **Deleted port** of the command to add **port 9000** as a rule to allow incoming connection in the Firewall
- [X] Deleted all references related to the port in the doc

## Evidence

I'm running a network requester and I don't obtain any output when I type this command

msg-1217675022-65876

### CODE REVIEW

**Comment by twofaktor** [comment]
@mfahampshire could you review this?

I'm not sure if keep these lines:

https://github.com/nymtech/nym/pull/3614/files#diff-6591210c152424cfba57ddee47466df812b24b15c5fc5f30c56acbf59c2309e0L252-L255

**Comment by mfahampshire** [comment]
@twofaktor Nadim no longer works for Nym - I will have a look.

**Comment by twofaktor** [comment]
> @twofaktor Nadim no longer works for Nym - I will have a look. 

Who is Nadim?

**Comment by twofaktor** [comment]
> @twofaktor Nadim no longer works for Nym - I will have a look.

aah, ok, sorry, I don't know why I mentioned him

**Review by mfahampshire — APPROVED** [review]

**Pull request merged**
