### PR TITLE
Feature/implicit runtime

### PR DESCRIPTION
**Pull request by jstuczyn**
Removes explicit construction of tokio runtimes in favour of implicit `#[tokio::main]`

### CODE REVIEW

**Comment by futurechimp** [comment]
Is it normal that this would fail tests on Windows? It seems to be failing a format check, but I'd have expected lots of other things to break.

**Review by futurechimp — CHANGES_REQUESTED** [review]
I'm not sure what's up with the Windows format checks, but as this one is just a bit of code grooming I'd rather leave it until after we cut 0.12.0 and merge it after that.

**Comment by jstuczyn** [comment]
> Is it normal that this would fail tests on Windows? It seems to be failing a format check, but I'd have expected lots of other things to break.

Those have already been broken for a while now - I have absolutely no idea why. I think @durch managed to fix those in one of his other PRs but I don't remember exactly how

**Comment by neacsu** [comment]
I've fixed it by removing a dangling rustfmt file: https://github.com/nymtech/nym/pull/975

**Review by neacsu — APPROVED** [review]

**Pull request merged**
