### PR TITLE
Add configurable http api port to gateway

### PR DESCRIPTION
**Pull request by neacsu**

### CODE REVIEW

**Comment by jstuczyn** [comment]
i imagine this will most likely get superseded by https://github.com/nymtech/nym/pull/3970 once merged. 
we'll want to have gateways/nym-nodes expose their API on one of predefined ports: 80/443 if properly setup with SSL (which will be obligatory down the line), or 8080 otherwise; so there's going to be no need to put anything in the contract

**Comment by neacsu** [comment]
> i imagine this will most likely get superseded by #3970 once merged. we'll want to have gateways/nym-nodes expose their API on one of predefined ports: 80/443 if properly setup with SSL (which will be obligatory down the line), or 8080 otherwise; so there's going to be no need to put anything in the contract

Given that, from what I last heard, it's not clear if we will have these ports on the gateway, or in a reverse proxy, having it configurable should still be ok.

**Review by durch — APPROVED** [review]

**Comment by jstuczyn** [comment]
> > i imagine this will most likely get superseded by #3970 once merged. we'll want to have gateways/nym-nodes expose their API on one of predefined ports: 80/443 if properly setup with SSL (which will be obligatory down the line), or 8080 otherwise; so there's going to be no need to put anything in the contract
> 
> Given that, from what I last heard, it's not clear if we will have these ports on the gateway, or in a reverse proxy, having it configurable should still be ok.

I think we should sync up with @mmsinclair on his current thoughts about that. because afaik we didn't want to put yet more data in the contract and nodes should have been using predictable ports. obviously, if operators wanted, they could set custom ports locally and expose the correct ones via proxy (but that's already covered by my feature)

**Comment by neacsu** [comment]
Ok, I'll close this PR then, as the customisable port will already be covered by another PR.

**Pull request closed without merging**
