### PR TITLE
[BUG] network requester documentation update

### PR DESCRIPTION
**Pull request by twofaktor**
# Description

Networks requester only have a connection with the gateway, not with mixed nodes (Mixnet) (`1789` port)

# Checklist:

- [X] Removed 1789 port from ufw rules in network requester documentation

tempsnip

imagen

src: https://nymtech.net/docs/nodes/network-requester-setup.html#ports

### CODE REVIEW

**Comment by mfahampshire** [comment]
@twofaktor please retarget to `release/v1.1.20` (the upcoming release)

**Review by mfahampshire — COMMENTED** [review]
lgtm, but see comment above re retargeting the PR branch

**Review by mfahampshire — APPROVED** [review]

**Comment by twofaktor** [comment]
> @twofaktor please retarget to `release/v1.1.20` (the upcoming release)

Could you explain me how retarget this PR?

**Comment by twofaktor** [comment]
> lgtm, but see comment above re retargeting the PR branch

I think that I got it, could you review that?

**Comment by twofaktor** [comment]
Ok, I reopened a new PR https://github.com/nymtech/nym/pull/3481 using the brach called "release/v1.1.20"

I think that all is OK, but I didn't can do better and I need new approval from you @mfahampshire

**Pull request closed without merging**
