### PR TITLE
Documentation/patch-variables

### PR DESCRIPTION
**Pull request by serinko**
# Description

Simplifies building from the latest version by checkout to master. 

# Checklist:

- [x] changed `platform_release_version` with `master`
- [x] deleted sandbox option
- [x] added `sh` code block specification as a proposal to keep larger code blocks cleaner (syntax vs comment layout)
- [x] corrected config path
- [x] change all the github links with `{{platform_release_version}}` to just use `master` (Not all of those should have been changed ofc, left where it made sense)
- [x] Update Monero guide in dev portal - will do on Monday
- [x] Add banners to all dev-portal NC user manuals
- [x] unify Socks5 address across NC user manuals

### CODE REVIEW

**Comment by serinko** [comment]
done with /docs, dev-portal and operators to go

**Comment by serinko** [comment]
All 3 books variables change - **DONE**

**Comment by serinko** [comment]
Done on my side

**Comment by mfahampshire** [comment]
lgtm :)

**Review by mfahampshire — APPROVED** [review]

**Comment by serinko** [comment]
Re-based to tomorrows release, all checks re-run and passed -> **MERGING**

**Pull request merged**
