### PR TITLE
[DOCS]: Updates, license correction, flow edit

### PR DESCRIPTION
**Pull request by serinko**
## Description

Routine updates of `/operators`, fixed syntax bugs, updated license in all `/documentation`, new license added to `/LICENSES`.

### CODE REVIEW

**Review by mfahampshire — APPROVED** [review]

**Comment by serinko** [comment]
Nice catch, thank you. 
After we sync up on the `greetings`let's merge it.

**Comment by serinko** [comment]
Strange, when I pushed my commit, the checks passed, then I pushed merge of your tweaks and it failed again.

**Comment by mfahampshire** [comment]
Greetings is broken right now - its something we're pulling in from elsewhere. We can ignore it

**Comment by mfahampshire** [comment]
Just run the ci and cd manually for now due to the annoying greeting failure and then we can merge it imo

**Pull request merged**
