### PR TITLE
Update isp-sheet.csv

### PR DESCRIPTION
**Pull request by JohnSmith-PrivacyRebels**
Added a few known VPS providers which (a) support crypto payment (b) allow TOR in some shape or form (c) more or less know for their stability. Will add more eventually.

### CODE REVIEW

**Comment by serinko** [comment]
Good job, are you finished? I will merge it.

**Comment by JohnSmith-PrivacyRebels** [comment]
Not yet, I rushed a bit to add the most reliable providers (in my experience) but the list goes on. It takes some time to check providers. Do you think it is worth merging it now and then I continue? Or wait until I populate the list? I am happy with either.

**Comment by serinko** [comment]
There is no rush. Take your time and ping me once you done.

**Comment by JohnSmith-PrivacyRebels** [comment]
Added a few more, this is it for now, feel free to merge @serinko

**Review by serinko — APPROVED** [review]

**Comment by serinko** [comment]
Shipping it!

**Pull request merged**
