### PR TITLE
[DOC]: CCC 23 event pages

### PR DESCRIPTION
**Pull request by serinko**
# Description

Tailored pages for CCC 2023 event

- [x] Landing page with TOC
    - [x] Mixnet Overview link + [ ] add pics from Nymsphere 
- [x] NymVPN Guide
    - [x] Install
    - [x] Run
    - [x] Test
    - [x] Submit results of testing 
- [x] FAQ
    - [x] Mixnet  & Rewards (links)
    - [x] docs, dev-portal, operators guide (links)
    - [x] Smoosh (links)
    - [x] Exit GW
    - [x] SDKs (links)
    - [x] Tailored questions (work out with Romain and Marc D.)

### CODE REVIEW

**Comment by serinko** [comment]
No need to review yet, there is more
 hard lifting needs to be done tomorrow

**Comment by serinko** [comment]
nym-vpn.md is done, going to the FAQ

**Comment by serinko** [comment]
renamed to correct 37c3, shall be fine now.

**Comment by serinko** [comment]
In my opinion the FAQ shall be sized up with more basic questions. 
Despite that, I would say to merge, build and promote this version and continue on Tuesday.

**Review by mmsinclair — APPROVED** [review]

**Pull request merged**
