### PR TITLE
Entry wireguard tickets

### PR DESCRIPTION
**Pull request by neacsu**
This change is [Reviewable](https://reviewable.io/reviews/nymtech/nym/4888)

### CODE REVIEW

**Review by octol — APPROVED** [review]
Looking good!

> Reviewed 20 of 35 files at r1, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym/4888#-:-O7T-BjuE6r2hvu3mi0H:br2sbr6)* status: all files reviewed, 2 unresolved discussions (waiting on @jstuczyn and @neacsu)

___
*[`common/authenticator-requests/src/error.rs` line 1 at r3](https://reviewable.io/reviews/nymtech/nym/4888#-O7SxPzl5STmSWlqocOR:-O7SxPzl5STmSWlqocOS:b-ldub1a) ([raw file](https://github.com/nymtech/nym/blob/c7e3d5c2a4acfdc21d555c0173401db3850a7f62/common/authenticator-requests/src/error.rs#L1)):*
> ```XML
> // Copyright 2023 - Nym Technologies SA <contact@nymtech.net>
> ```

super duper nitpick: 2024
___
*[`common/authenticator-requests/src/v2/conversion.rs` line 9 at r3](https://reviewable.io/reviews/nymtech/nym/4888#-O7Sxz263tSLpLOEHrFq:-O7Sxz263tSLpLOEHrFr:bypqiir) ([raw file](https://github.com/nymtech/nym/blob/c7e3d5c2a4acfdc21d555c0173401db3850a7f62/common/authenticator-requests/src/v2/conversion.rs#L9)):*
> ```XML
>     fn from(authenticator_request: v1::request::AuthenticatorRequest) -> Self {
>         Self {
>             version: 2,
> ```

Should we take this opportunity to move the Authenticator messages to it's own dedicated band of version numbers? Possibly `2 -> 102`? Or we just skip that and add another tag indicating the protocol (ipr, authenticator)?
___
*[`service-providers/authenticator/src/mixnet_listener.rs` line 256 at r3](https://reviewable.io/reviews/nymtech/nym/4888#-O7Szq5V41DcbNNTHbqQ:-O7Szq5V41DcbNNTHbqR:br7fvrt) ([raw file](https://github.com/nymtech/nym/blob/c7e3d5c2a4acfdc21d555c0173401db3850a7f62/service-providers/authenticator/src/mixnet_listener.rs#L256)):*
> ```XML
>                     .remove_peer(&final_message.gateway_client)
>                     .await
>                     .tap_err(|err| {
> ```

Can do this with `inspect_err` nowadays, so no need for the tap crate

**Review by neacsu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym/4888)* status: all files reviewed, 1 unresolved discussion (waiting on @jstuczyn and @octol)

___
*[`common/authenticator-requests/src/v2/conversion.rs` line 9 at r3](https://reviewable.io/reviews/nymtech/nym/4888#-O7Sxz263tSLpLOEHrFq:-O7T7g-9C0UtekwOGUoT:bwqj6ho) ([raw file](https://github.com/nymtech/nym/blob/c7e3d5c2a4acfdc21d555c0173401db3850a7f62/common/authenticator-requests/src/v2/conversion.rs#L9)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

Should we take this opportunity to move the Authenticator messages to it's own dedicated band of version numbers? Possibly `2 -> 102`? Or we just skip that and add another tag indicating the protocol (ipr, authenticator)?
</blockquote></details>

I think it's worth including the tag in this one, why not. As a note, it's more important on the response side, as the client could (currently it doesn't) be multiplexing the mixnet connection. On the request side, it should be separated because of the nym address factor, but for consistency, I will add it to both entry and exit.
I'm thinking to add this protocol tag (with version and type) for this version just for authenticator, with a common struct that could be used by ipr and nr later respectively, when there are individual version changes for them, in their respective PRs. That way it wouldn't side track this PR.

**Review by octol — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym/4888)* status: all files reviewed, 1 unresolved discussion (waiting on @jstuczyn and @neacsu)

___
*[`common/authenticator-requests/src/v2/conversion.rs` line 9 at r3](https://reviewable.io/reviews/nymtech/nym/4888#-O7Sxz263tSLpLOEHrFq:-O7TCrMyEyEv8WkZqqhB:b-d2y35q) ([raw file](https://github.com/nymtech/nym/blob/c7e3d5c2a4acfdc21d555c0173401db3850a7f62/common/authenticator-requests/src/v2/conversion.rs#L9)):*
<details><summary><i>Previously, neacsu (Bogdan-Ștefan Neacşu) wrote…</i></summary><blockquote>

I think it's worth including the tag in this one, why not. As a note, it's more important on the response side, as the client could (currently it doesn't) be multiplexing the mixnet connection. On the request side, it should be separated because of the nym address factor, but for consistency, I will add it to both entry and exit.
I'm thinking to add this protocol tag (with version and type) for this version just for authenticator, with a common struct that could be used by ipr and nr later respectively, when there are individual version changes for them, in their respective PRs. That way it wouldn't side track this PR.
</blockquote></details>

Yep sounds like a good plan!

**Comment by benedettadavico** [comment]
The behaviour of the nodes and vpn client (as a test) has not changed, it still works as it used to. Obtaining ticketbooks also is unchanged

**Pull request merged**
