### PR TITLE
Setup basic test for mixnode stats reporting

### PR DESCRIPTION
**Pull request by octol**
Part of: https://github.com/nymtech/nym/issues/2059

### CODE REVIEW

**Comment by jstuczyn** [comment]
It looks like those new tests are not passing?

**Comment by octol** [comment]
> It looks like those new tests are not passing?

Yeah that assert for the transient state is iffy, removed for now

**Comment by jstuczyn** [comment]
Furthermore, I'm not really a fan of calling `sleep` inside the test code. Couldn't we just "advance" time without waiting for it? I.e. take a look at: https://docs.rs/tokio/latest/tokio/time/fn.advance.html

**Comment by octol** [comment]
> Furthermore, I'm not really a fan of calling `sleep` inside the test code. Couldn't we just "advance" time without waiting for it? I.e. take a look at: https://docs.rs/tokio/latest/tokio/time/fn.advance.html

Updated to use this instead. However this depends on `test-util` in tokio (and `time`).

**Comment by octol** [comment]
> > Furthermore, I'm not really a fan of calling `sleep` inside the test code. Couldn't we just "advance" time without waiting for it? I.e. take a look at: https://docs.rs/tokio/latest/tokio/time/fn.advance.html
> 
> Updated to use this instead. However this depends on `test-util` in tokio (and `time`).

and also `resolver = 2`

**Comment by octol** [comment]
See https://github.com/nymtech/nym/pull/1086 for changing to rust edition 2021, with which we can drop `resolver = 2`

**Review by jstuczyn — APPROVED** [review]

**Comment by octol** [comment]
> See #1086 for changing to rust edition 2021, with which we can drop `resolver = 2`

Seems like we still need `resolver = 2`, even after merging #1086. Looking at compiler output it still pulls in dev-dependency features. Maybe deps also need to opt-in to 2021 for it to work automatically

**Pull request merged**
